### ISSUE TITLE
Add bandit to pre-commit

### ISSUE THREAD

**Issue by drsm79** [ComplianceAsCode/auditree-framework#100]
## Overview

Catch any unwanted security issues.

## Requirements
- Bandit runs as part of the pre-commit via https://github.com/Lucas-C/pre-commit-hooks-bandit

## Approach

_Provide a detailed approach to satisfy all of the requirements listed in the
previous section.  This level of detail may not be available at the time of
issue creation and can be completed at a later time._

## Security and Privacy

_Provide the impact on security and privacy as it relates to the completion of
this issue.  This level of detail may not be available at the time of
issue creation and can be completed at a later time.  N/A if not applicable._

## Test Plan

_Provide the test process that will be followed to adequately verify that the
approach above satisfies the requirements provided.  This level of detail may
not be available at the time of issue creation and can be completed at a later
time._

**Comment by alfinkel** [comment]
https://github.com/PyCQA/bandit might be better to use
