### ISSUE TITLE
Ability to specify fetchers to run

### ISSUE THREAD

**Issue by Tang8330** [ComplianceAsCode/auditree-framework#103]
## Overview

_Provide a high level summary of the issue to be resolved.  This is mandatory
for issue creation._

Lack of granularity around running fetchers. We should be able to specify which fetcher to run and which fetcher task to run.

**Comment by Tang8330** [comment]
Example use cases:
1. Run the G suite fetcher
2. Run the G suite fetcher to pull the list of users and whether they have MFA turned on

**Comment by alfinkel** [comment]
Targeted fetcher execution is documented [here](https://complianceascode.github.io/auditree-framework/design-principles.html#fetcher-execution).

**Comment by alfinkel** [comment]
Closing this issue as I think the request/question has been answered.  You can reopen if you disagree.
