### ISSUE TITLE
Need access for the auditree-framework for contributing

### ISSUE THREAD

**Issue by xinivanchen** [ComplianceAsCode/auditree-framework#11]
I would like collaborator (write) access to this repository, so I can contribute
to the Auditree Framework.

 - [X] I have read the [contributing guidelines][CONTRIBUTING]

[CONTRIBUTING]: https://github.com/ComplianceAsCode/auditree-framework/blob/master/CONTRIBUTING.md

**Comment by alfinkel** [comment]
done

**Comment by alfinkel** [comment]
We've changed our approach a bit for collaborators.  If you want to contribute to the framework just fork the repo and PR your change.  If you become a consistent and regular contributor then you can look to becoming a collaborator.  See the https://github.com/ComplianceAsCode/auditree-arboretum/blob/main/CONTRIBUTING.md for more details.
