### ISSUE TITLE
Record how evidence is generated

### ISSUE THREAD

**Issue by cobu2b** [ComplianceAsCode/auditree-framework#125]
## Overview

During an audit, an auditor often asks an auditee to provide a screen shot to show an evidence is generated. A fetcher should have an ability to track which APIs and parameters are used to generated the evidence. This feature is part of [chain of custody](https://www.geeksforgeeks.org/chain-of-custody-digital-forensics/) in digital forensics. 

## Requirements

- Record API calls including method, endpoint, and parameters
- Associate the sequence of the API calls with the evidence
- Prevent the chain of custody from being modified

## Approach

We could leverage locker or add a new component for forensics. We then update a service function to record the sequence of the API calls while generating the evidence. At the fetcher class level , we can update the object for forensics with the output from the service function.

## Security and Privacy

The sequence of the API calls could expose sensitive data. The protection or masking of the data is required. 

## Test Plan

We can utilize the sequence of the API calls to produce an evidence and compare it with the evidence in a file.

**Comment by alfinkel** [comment]
This is an interesting proposal but I'm not sure that we can build something that guarantees the "chain of custody" you mention as the premise for this issue.  For instance, tracking the API calls made to gather a piece of evidence doesn't track possible manipulation of that evidence by fetcher code prior to adding that evidence to a locker.  This breaks that "chain of custody" premise.

However, a limited form of "chain of custody" _may_ be of some value.  **I think one thing that could be done is to track the fetcher used to gather an evidence in the `index.json` evidence metadata.  This is something we don't do today but it would be fairly easy to implement.**  Another possibility could be to leverage the fetcher's session method to track those API calls and store them in the `index.json` evidence metadata.  This of course relies on the author of the fetcher using the session object rather their own request mechanism to ensure chain of custody.  Doing this may have some value although does introduce a pretty significant technical challenge when dealing with fetchers that gather multiple pieces of evidence.  Finally, I suppose you could build a general metadata update method on the ComplianceFetcher that allows a fetcher author to add whatever evidence metadata they wish which could include chain of custody API call content but TBH that seems a bit hacky.

Like I said, this is an interesting proposal and perhaps I'm just looking at things with blinders on.  So if you have other ideas that I didn't touch upon I'd love to hear them.

**Comment by cobu2b** [comment]
@alfinkel Thank you for your insight. I agree with your points. We could not track all data manipulations. Recording how we gather data in text (at a fetcher class), API endpoints, parameters, and the timestamps (at a service function) would be valuable for audits. Based on your explanation, using a fetcher's session would be a solution so that we can  track those API calls and store them in the index.json evidence metadata. 

Referring to etch_recent_pull_requests.py, RepoCommitEvidence should be used to updated index.json. Should we pass the RepoCommitEvidence's object to the service function?

**Comment by alfinkel** [comment]
> Referring to etch_recent_pull_requests.py, RepoCommitEvidence should be used to updated index.json. Should we pass the RepoCommitEvidence's object to the service function?

Sorry I don't know what `fetch_recent_pull_requests.py` is and I'm not sure I follow what service function you're referring to.

**Comment by cobu2b** [comment]
Thank you for your quick response, Al. I am sorry for confusion. I referred to this [file](https://github.com/ComplianceAsCode/auditree-arboretum/blob/main/arboretum/auditree/fetchers/github/fetch_recent_commits.py). When  GithubRepoCommitsFetche gets evidence in JSON format, it will call [github.get_commit_details](https://github.com/ComplianceAsCode/auditree-arboretum/blob/main/arboretum/auditree/fetchers/github/fetch_recent_commits.py#L85). The function [get_commit_details](https://github.com/ComplianceAsCode/auditree-framework/blob/main/compliance/utils/services/github.py#L398) is under services folder so I called it a service function. Please kindly let me know how we should call them so that we use the same terms. Thank you again for your help.

**Comment by alfinkel** [comment]
closing...
