### ISSUE TITLE
Problems occur when following README directions in Try It section

### ISSUE THREAD

**Issue by degenaro** [ComplianceAsCode/auditree-framework#133]
## Overview

Two issues following the directions of the README with respect to the Try It section:

1. `python -m venv`

The command should be `python -m venv venv`

2. compliance --fetch --evidence local -C auditree_demo.json -v
...
Fetch the universal time. - ran in: 0.000s

====================================================================
ERROR: fetch_auditree_logo (demo_examples.fetchers.fetch_auditree_logo.ImageFetcher)
Fetch the Auditree logo.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/degenaro/git/auditree-framework/demo/venv/lib/python3.9/site-packages/compliance/evidence.py", line 824, in wrapper
    return _store_wrapper(self, evidence_path, f, 'raw')
  File "/home/degenaro/git/auditree-framework/demo/venv/lib/python3.9/site-packages/compliance/evidence.py", line 977, in _store_wrapper
    evidence.set_content(content)
  File "/home/degenaro/git/auditree-framework/demo/venv/lib/python3.9/site-packages/compliance/evidence.py", line 226, in set_content
    self._content.encode()
AttributeError: 'bytes' object has no attribute 'encode'

----------------------------------------------------------------------
Ran 6 tests in 0.004s

FAILED (errors=1)

`Note that error occurs using Python 3.9.9.`

## Requirements

- correct python -m venv command is provided in the README
- code is fixed so that error does not occur

## Approach

TBD

## Security and Privacy

N/A

## Test Plan

TBD

**Comment by cletomartin** [comment]
I believe these 2 problems are fixed now. Thanks!
