### ISSUE TITLE
Collaborator access request.

### ISSUE THREAD

**Issue by butler54** [ComplianceAsCode/auditree-framework#26]
I would like collaborator (write) access to this repository, so I can contribute
to the Auditree Framework.

 - [x] I have read the [contributing guidelines][CONTRIBUTING]

[CONTRIBUTING]: https://github.com/ComplianceAsCode/auditree-framework/blob/master/CONTRIBUTING.md

**Comment by drsm79** [comment]
Going to close this as I understand the need is actually just to PR some typo fixes. We've updated the contributor request to make it clearer that its more like becoming an Apache committer than required to contribute. Sorry for the confusion @butler54 :)
