### ISSUE TITLE
Push evidence to remote locker after fetchers run

### ISSUE THREAD

**Issue by alfinkel** [ComplianceAsCode/auditree-framework#36]
## Overview

Currently remote locker pushes are performed at the end of the check phase.  We should also push to the remote locker after the fetch phase.

## Requirements

- Push locker after fetch phase is complete
- The local locker should be reconciled with the remote locker before any push (after fetcher process and after check process)

## Approach

TBD

## Security and Privacy

N/A

## Test Plan

TBD

**Comment by alfinkel** [comment]
I'm not entirely sure that this makes sense to do.  What do you think @drsm79?

**Comment by drsm79** [comment]
I think with the changes to how the cli runs etc. it's probably moot. Close?

**Comment by alfinkel** [comment]
reopening to leverage functionality adding in #85 and satisfy a requirement to separate the execution of fetchers across multiple multiple CI build jobs.

**Comment by alfinkel** [comment]
Additionally as part of this task we need to ensure that the local locker is in sync with the remote in cases where fetcher build jobs are running in parallel.
