### ISSUE TITLE
Update demo instructions

### ISSUE THREAD

**Issue by alfinkel** [ComplianceAsCode/auditree-framework#70]
## Overview

The "Try It" section of the README as well as the Quick Start guide in the docs need to be updated.  There no longer is a doc or doc/demo-checks.  We should add another demo, kick-the-tires set of f/c's and update the documentation accordingly or remove the "Try It" section from the README and any refs to the demo in the quick start docs.

## Requirements

See overview

## Approach

TBD

## Security and Privacy

N/A

## Test Plan

- If implementing a demo set of f/c's, instructions should work

**Comment by drsm79** [comment]
Ideally the demo is run as part of CI actions.
