### ISSUE TITLE
Add support for binary evidence

### ISSUE THREAD

**Issue by alfinkel** [ComplianceAsCode/auditree-framework#87]
## Overview

We should add support for gathering binary evidence.  A need arose for fetching excel spreadsheets.

## Requirements

- ~~Add BinaryEvidence~~
   - ~~To be used with fetching evidence only~~
   - ~~Add appropriate decorator~~
   - ~~Add appropriate context manager~~
- Add a binary content flag to RawEvidence
- Update locker to write binary content

## Approach

TBD

## Security and Privacy

N/A

## Test Plan

TBD

**Comment by aslomoi** [comment]
We have excel (both `.xls` and `.xlsx`) files that we need to dynamically fetch from a remote source and eventually parse into a harvest report. It would be helpful to be able to do the following (or similar):
```
# source is a pathlib.Path to an excel file
content = source.read_bytes()
...
with raw_evidence(...) as raw:
  raw.set_content(content)
```
This would help in maintaining the file as excel-readable in the locker without extra encoding / lossiness.

At the moment the above gives the following error:
```
Traceback (most recent call last):
  File ".../fetch_excel.py", line 80, in fetch_excel
    logging.error('Raw evidence error. Evidence is empty')
  File "/usr/local/lib/python3.9/site-packages/compliance/evidence.py", line 259, in __exit__
    self.locker.add_evidence(self.evidence)
  File "/usr/local/lib/python3.9/site-packages/compliance/locker.py", line 226, in add_evidence
    f.write(evidence.content)
TypeError: write() argument must be str, not bytes
```
