### ISSUE TITLE
Replace os.path with pathlib

### ISSUE THREAD

**Issue by alfinkel** [ComplianceAsCode/auditree-framework#89]
## Overview

We should replace the use of os.path with [pathlib](https://docs.python.org/3/library/pathlib.html) wherever possible throughout the framework.

## Requirements

see overview

## Approach

- TBD or Handle as part of other work (for example this was already done to the report and evidence modules as part of other related work)

## Security and Privacy

N/A

## Test Plan

TBD

**Comment by drsm79** [comment]
For the binary stuff you have write_text and write_bytes.
