### ISSUE TITLE
Request to become a collaborator.

### ISSUE THREAD

**Issue by tsehrer** [ComplianceAsCode/auditree-framework#92]
I would like collaborator (write) access to this repository.

- [x] I have read the [contributing guidelines][CONTRIBUTING]
- [x] I understand the responsibilities of a collaborator are to:
  - help review contributions to the Auditree Framework
  - help make & test releases
  - help promote the project

[CONTRIBUTING]: https://github.com/ComplianceAsCode/auditree-framework/blob/master/CONTRIBUTING.md

**Comment by alfinkel** [comment]
Have a look in the [CONTRIBUTING.md](https://github.com/ComplianceAsCode/auditree-framework/blob/main/CONTRIBUTING.md) for contributing guidelines.  In a nutshell you can `Make a fork of the repository & file a Pull Request from your fork with the changes`.

It would also be good to have an issue opened detailing your proposed change before providing a PR.
