### ISSUE TITLE
Add change to enable GitHub Issues notifier to create issues based on a subset of checks.

### ISSUE THREAD

**Issue by tsehrer** [ComplianceAsCode/auditree-framework#93]
## Overview

- I would like the GitHub Issues notifier to be able to notify against a subset of checks for a given accreditation.

## Requirements

- If specific checks are configured within a given accreditation `GHIssuesNotifier` should only create issues for those specific checks.

## Approach

- Add logic to `GHIssuesNotifier.__generate_issues` to look for a non-empty `checks` configuration element within a given accreditation and then only generate issues for the specified checks if it's found.

## Security and Privacy

N/A

## Test Plan

N/A

**Comment by alfinkel** [comment]
See also #37
